{% set name = "visdom" %}
{% set version = "0.1.8.5" %}
{% set hash_type = "sha256" %}
{% set hash = "e9afccf5b64a856d70e2538352a010024324fccaa093df8f3d7890755869136b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - numpy
    - scipy
    - pillow
    - requests
    - tornado
    - pyzmq
    - six
    - torchfile
    - websocket-client

test:
  imports:
    - visdom

about:
  home: https://github.com/facebookresearch/visdom
  license: CC BY 4.0
  license_family: OTHER
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A tool for visualizing live, rich data for Torch and Numpy.
  description: |
    A flexible tool for creating, organizing, and sharing visualizations
    of live, rich data. Supports Torch and Numpy.
  dev_url: https://github.com/facebookresearch/visdom

extra:
  recipe-maintainers:
    - andfoy
