{% set name = "visdom" %}
{% set version = "0.1.7" %}
{% set hash_type = "sha256" %}
{% set hash = "62732c1e912b8a0819cb3c69a429d0360c291559511ff99932f12bd3f1d1a8bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - pillow
    - requests
    - tornado
    - pyzmq
    - six

test:
  imports:
    - visdom

about:
  home: https://github.com/facebookresearch/visdom
  license: CC BY 4.0
  license_family: OTHER
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A tool for visualizing live, rich data for Torch and Numpy.
  description: |
    A flexible tool for creating, organizing, and sharing visualizations
    of live, rich data. Supports Torch and Numpy.
  dev_url: https://github.com/facebookresearch/visdom

extra:
  recipe-maintainers:
    - andfoy
