travis:
  secure:
    BINSTAR_TOKEN: rqDTLv9RxTF85Qc3YexwPt9N9Hk7CZJ/BApA6lpJMq6sPTVYPnkYoFWVRVhHcFo3iykrBE0aI9WRV3kokCYo6aIx2oWQ+S0SKr2IJb4N+OpoWEXoIINhCxemgdB91JwnnZ43oCVM5XBj5M91igyjDFB/e3JQnOMPX2L0P23lL7aEai6kzAldS5H0gdIgpfZMqYWS177PtoL33G+W06DB041J9PE+L1iHHgZdgmqfTA7bwsuCmYKcSVigcofUTYzDpTxR42U2DTi70T6p4KL6X10lPvWKkng0bfrNyUOircEBt7tyqjhRnyIsKMZEOCxAHZC+MiL0CfuKDlytpEbK7TFjqqPwnlkcryxY4MhzFyDZcbrE/dwjVZNAdDFMlWd8mz05ZyccOZbwBBH76o1DGwXno51n5TytuekbGrwxhqrfVpLRdbzEqgAs1tCqBzovPDgWWlQmEnwQfML7ok2pIXyaBakYwkoMuyyZkQxpnInqk+mUPlWkagVahQlGIwhlhh9usnaog8VrAF57GOL54c5hgSPTHjHa8uUE1eSC20z4yB8FCWML4pPDgIY9j7fHptltPnX+S8UiDuOyWHlZmFj3xQmT1iPoDH5LVc3I91qWgMzKOkMq8pCNj5WZTjeCkZ5XKMc2m/R1FwqeTSQh9eUy2eEp6s8uFw1D1dmm7Hg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
