travis:
  secure:
    BINSTAR_TOKEN: I4lLn3B43pbZ3plfe8oKzSmXg7wLutzem4VleYGzsek9Zm3cA3yIQkRh7fVaxLokquDXtoxBmxeyyYdlm+3hmkQr4amUKn8SPH+9RHA1BBOE0UDPToin7YqOtF13yN2nSkmfEBKd89Nu7GaIQc8HTMYKCkCjprdhHtbOn0Y74NDsDoomnzyhBZ5WwVyxAGbFmtP5yh1ubZF1B6irRCrKRY8hYBlqbNGP7sWSF57rw/0ErcV4MnKpggjrSTE9at4cJY5qL9r/aJCNsfa4Xct8CbZkQpoFmeWKNE+vciH+g7xmnVTSM092RnpgOZ5R+rqI+sH2f9qA8OHpR+vEmNrYW3SYQpAWfvhlES3nYBBwbQYeVl4uECHdvUqSozEmLSV4s8vMglDiYSOU//SJFWHFdha94zapdTmHIBPa+FSdtX5vSAcp4rjQVHFJxCWMamYV6U0Wbfi/GhOblof9+iFRUt7XcdUAv7OfpF4LljNiGvVcdzSjzGhy2gzVp6Z0xuHiIIvKgIJmsTP7xbnP/9ukC8HfHgmJZrnsrL6cEsfxdpioitRAX+UMtN4UIPVF0/jTW4UZZNz5Lk/ccpk2NNuEcesfApmpwWMWKOPIGo+YV90/dtHk6YnSyA3to+o4qqT75mLAeuAf3z6NrHROpM5NlKtngU2oRyfF6E7hicJYKWM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
